spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:haobaxucan/microservicecloud-config.git



server:
  port: 3344

eureka:
  client:
    service-url:
      defaultZone: http://eureka.springcloud.cn/eureka/


